import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import WorkExperience from '@/components/WorkExperience'
import Skills from '@/components/Skills'
import ContactMe from '@/components/ContactMe'
import Link from 'next/link'
import { HomeIcon } from '@heroicons/react/24/solid';
import { GetStaticProps } from 'next'
import { Experience, PageInfo, Project, Skill, Social } from '@/typings'
import { createClient } from "next-sanity";
import Projects from '@/components/Projects'

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
}

const client = createClient({
  projectId: 've8fo00y',
  dataset: "production",
  apiVersion: "2023-03-11",
  useCdn: false
});

const inter = Inter({ subsets: ['latin'] })

export default function Home({ pageInfo, experiences, projects, skills, socials }: Props) {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]'>
      <Head>
        <title>Joshs Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />

      <section id="hero" className='snap-start'>
        <Hero pageInfo={pageInfo} />
      </section>

      <section id='about' className='snap-center'>
        <About pageInfo={pageInfo} />
      </section>

      <section id='experience' className='snap-center'>
        <WorkExperience experiences={experiences} />
      </section>

      <section id='skills' className='snap-center'>
        <Skills skills={skills} />
      </section>

      {/* Projects */}
      <section id='projects' className='snap-center'>
        <Projects projects={projects} />
      </section>

      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>


      <footer className='sticky bottom-5 w-full'>
        <div className='flex items-center justify-center'>
          <Link href='#hero' className='cursor-pointer'>
            <HomeIcon className='h-5 w-5 rounded-full filter grayscale hover:text-gray-500' />
          </Link>
        </div>
      </footer>


    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await client.fetch(`*[_type == "pageInfo"][0]`);
  const experiences: Experience[] = await client.fetch(`*[_type == "experience"] {..., technologies[]->}`);
  const skills: Skill[] = await client.fetch(`*[_type == "skill"]`);
  const projects: Project[] = await client.fetch(`  *[_type == "project"] {..., technologies[]-> }`);
  const socials: Social[] = await client.fetch(` *[_type == "social"] `);

  return {
    props: {
      pageInfo,
      experiences,
      skills,
      projects,
      socials,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every ten seconds
    revalidate: 10,
  }
}
